const DESTINATION_EMAIL='isabela.lima@senaicni.com.br',MIN=3,MAX=10,MC=5*1024*1024,MA=10*1024*1024,MT=25*1024*1024;
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}}),clean=v=>String(v||'').trim(),ext=n=>(n||'').toLowerCase().split('.').pop(),email=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e),upload=v=>v&&typeof v.arrayBuffer==='function'&&typeof v.name==='string';
function b64(buf){const a=new Uint8Array(buf);let s='';for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,Math.min(i+32768,a.length)));return btoa(s)}
async function attachment(f){return{filename:f.name,content:b64(await f.arrayBuffer())}}
async function submit(request,env){
 if(!env.RESEND_API_KEY||!env.FROM_EMAIL)return json({error:'O envio de e-mail ainda não foi configurado no Cloudflare. Configure RESEND_API_KEY e FROM_EMAIL.'},500);
 let fd;try{fd=await request.formData()}catch{return json({error:'Não foi possível ler os dados enviados.'},400)}
 const team=clean(fd.get('teamName')),phone=clean(fd.get('phone')),mail=clean(fd.get('email')),members=fd.getAll('members').map(clean).filter(Boolean),concept=fd.get('conceptFile'),arts=fd.getAll('artFiles').filter(upload);
 if(!team)return json({error:'Informe o nome da equipe.'},400);if(members.length<MIN)return json({error:'Informe pelo menos 3 integrantes.'},400);if(members.length>MAX)return json({error:'O limite é de 10 integrantes.'},400);
 const pd=phone.replace(/\D/g,'');if(pd.length<10||pd.length>13)return json({error:'Informe um telefone válido com DDD.'},400);if(!email(mail))return json({error:'Informe um e-mail válido.'},400);
 if(!upload(concept)||!concept.name)return json({error:'Anexe a apresentação do conceito.'},400);if(!['pdf','ppt','pptx'].includes(ext(concept.name)))return json({error:'A apresentação deve estar em PDF, PPT ou PPTX.'},400);if(concept.size>MC)return json({error:'A apresentação deve ter no máximo 5 MB.'},400);
 if(!arts.length)return json({error:'Anexe pelo menos um arquivo de arte.'},400);if(arts.some(f=>!['pdf','png','jpg','jpeg'].includes(ext(f.name))))return json({error:'As artes devem estar em PDF, PNG, JPG ou JPEG.'},400);if(arts.some(f=>f.size>MA))return json({error:'Cada arte deve ter no máximo 10 MB.'},400);if(concept.size+arts.reduce((s,f)=>s+f.size,0)>MT)return json({error:'O total dos anexos deve ser de no máximo 25 MB.'},400);
 const at=[await attachment(concept),...await Promise.all(arts.map(attachment))],subject='FIRST CANOPY — Proposta de troféu — '+team,text='Equipe: '+team+'\nTelefone: '+phone+'\nE-mail: '+mail+'\n\nIntegrantes:\n'+members.map((m,i)=>(i+1)+'. '+m).join('\n');
 const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:env.FROM_EMAIL,to:[DESTINATION_EMAIL],cc:[mail],reply_to:mail,subject,text,attachments:at})});let d={};try{d=await r.json()}catch{}if(!r.ok){console.error('Resend',r.status,d);return json({error:'A proposta não pôde ser enviada por e-mail.'},502)}return json({ok:true,id:d.id||null})
}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/api/submit'){if(request.method!=='POST')return json({error:'Método não permitido.'},405);return submit(request,env)}return env.ASSETS.fetch(request)}};