const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const form=$('#proposalForm'),list=$('#memberList'),next=$('#next'),back=$('#back'),submit=$('#submitProposal'),msg=$('#formMessage');let step=0;
const value=id=>$(id).value.trim(),error=(id,text)=>{$(id).textContent=text},invalid=(el,b)=>el.classList.toggle('invalid',b),ext=f=>f?.name.toLowerCase().split('.').pop();
function renumber(){$$('.member',list).forEach((row,i)=>{$('i',row).textContent=i+1;$('.member-name',row).placeholder=`Nome completo do integrante ${i+1}`});$('#addMember').disabled=$$('.member',list).length>=10}
list.onclick=e=>{if(!e.target.matches('.remove'))return;if($$('.member',list).length<=3){error('#membersError','É necessário manter pelo menos 3 integrantes.');return}e.target.closest('.member').remove();renumber();validate(0,false)};
$('#addMember').onclick=()=>{if($$('.member',list).length>=10)return;const row=document.createElement('div');row.className='member';row.innerHTML='<i></i><input class="member-name" name="members" required><button type="button" class="remove" aria-label="Remover integrante">×</button>';list.append(row);renumber()};renumber();
function field(id,message,show){const el=$(id),ok=!!el.value.trim();invalid(el,show&&!ok);error(id+'Error',show&&!ok?message:'');return ok}
function validate(n,show=true){let ok=true;if(n===0){ok=field('#teamName','Informe o nome da equipe.',show)&&ok;const members=$$('.member-name',list),filled=members.filter(x=>x.value.trim());const mok=filled.length>=3&&members.every(x=>x.value.trim());members.forEach(x=>invalid(x,show&&!x.value.trim()));error('#membersError',show&&!mok?'Preencha o nome completo de todos os integrantes (mínimo de 3).':'');ok=mok&&ok;const phone=value('#phone').replace(/\D/g,''),pok=phone.length>=10&&phone.length<=13;invalid($('#phone'),show&&!pok);error('#phoneError',show&&!pok?'Informe um telefone válido com DDD.':'');ok=pok&&ok;const eok=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value('#email'));invalid($('#email'),show&&!eok);error('#emailError',show&&!eok?'Informe um e-mail válido.':'');ok=eok&&ok}
if(n===1){for(const [id,label] of [['#proposalName','Informe o nome da proposta.'],['#proposalDescription','Descreva a proposta.'],['#materials','Informe os materiais e técnicas.']])ok=field(id,label,show)&&ok}
if(n===2){const art=[...$('#artFiles').files],concept=$('#conceptFile').files[0],docs=$('#docsFile').files[0],size=art.reduce((s,f)=>s+f.size,0)+(concept?.size||0)+(docs?.size||0);let a=art.length>0&&art.every(f=>['pdf','png','jpg','jpeg'].includes(ext(f))&&f.size<=10*1048576);let c=!!concept&&['pdf','ppt','pptx'].includes(ext(concept))&&concept.size<=5*1048576;let d=!!docs&&ext(docs)==='pdf'&&docs.size<=10*1048576;error('#artsError',show&&!a?'Envie ao menos uma imagem válida de até 10 MB por arquivo.':'');error('#conceptError',show&&!c?'Envie uma apresentação PDF, PPT ou PPTX de até 5 MB.':'');error('#docsError',show&&!d?'Envie um PDF complementar de até 10 MB.':'');error('#docsError',show&&a&&c&&d&&size>25*1048576?'O total dos anexos deve ser de no máximo 25 MB.':$('#docsError').textContent);ok=a&&c&&d&&size<=25*1048576}
return !!ok}
function showStep(n){step=n;$$('.panel').forEach((p,i)=>p.hidden=i!==n);$$('.step').forEach((s,i)=>{s.classList.toggle('active',i===n);s.classList.toggle('done',i<n);$('b',s).textContent=i<n?'✓':i+1});back.hidden=n===0;next.hidden=n===3;submit.hidden=n!==3;msg.className='message';if(n===3)review();form.scrollIntoView({behavior:'smooth',block:'start'})}
function review(){const r=$('#review');r.replaceChildren();for(const [name,data] of [['Equipe',value('#teamName')],['Integrantes',$$('.member-name',list).map(x=>x.value.trim()).join(', ')],['Telefone',value('#phone')],['E-mail',value('#email')],['Proposta',value('#proposalName')],['Descrição',value('#proposalDescription')],['Materiais e técnicas',value('#materials')],['Imagem / artes',[...$('#artFiles').files].map(x=>x.name).join(', ')],['Apresentação',$('#conceptFile').files[0]?.name],['Documentação',$('#docsFile').files[0]?.name]]){const item=document.createElement('div'),b=document.createElement('strong'),p=document.createElement('p');b.textContent=name;p.textContent=data;item.append(b,p);r.append(item)}}
next.onclick=()=>{if(!validate(step,true)){msg.textContent='Preencha todos os itens obrigatórios desta etapa para continuar.';msg.className='message error';return}showStep(step+1)};back.onclick=()=>showStep(step-1);
form.addEventListener('input',e=>{if(e.target.id==='phone'){let d=e.target.value.replace(/\D/g,'').slice(0,11);e.target.value=d.length<=2?(d?'('+d:''):d.length<=6?'('+d.slice(0,2)+') '+d.slice(2):d.length<=10?'('+d.slice(0,2)+') '+d.slice(2,6)+'-'+d.slice(6):'('+d.slice(0,2)+') '+d.slice(2,7)+'-'+d.slice(7)}$('#descriptionCount').textContent=$('#proposalDescription').value.length+'/1000';$('#materialsCount').textContent=$('#materials').value.length+'/500';validate(step,false)});
for(const [id,name,box] of [['#artFiles','#artsName','#artsBox'],['#conceptFile','#conceptName','#conceptBox'],['#docsFile','#docsName','#docsBox']]){const input=$(id),drop=$(box);input.onchange=()=>{$(name).textContent=[...input.files].map(f=>f.name).join(' • ')||'Nenhum arquivo selecionado.';drop.classList.toggle('has-file',!!input.files.length);validate(2,false)};drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');input.files=e.dataTransfer.files;input.dispatchEvent(new Event('change'))}}
form.onsubmit=async e=>{e.preventDefault();for(let i=0;i<3;i++)if(!validate(i,true)){showStep(i);validate(i,true);msg.textContent='Revise os itens obrigatórios antes de enviar.';msg.className='message error';return}submit.disabled=true;submit.textContent='Enviando...';try{const response=await fetch('/api/submit',{method:'POST',body:new FormData(form)});let data={};try{data=await response.json()}catch{}if(!response.ok)throw Error(data.error||'Não foi possível enviar a proposta.');$('#successText').textContent=`A proposta foi registrada com o ID ${data.proposalId}.`;$('#successModal').classList.add('open');$('#successModal').setAttribute('aria-hidden','false')}catch(err){msg.textContent=err.message;msg.className='message error'}finally{submit.disabled=false;submit.textContent='Enviar proposta  →'}};
$('#closeSuccess').onclick=()=>{$('#successModal').classList.remove('open');$('#successModal').setAttribute('aria-hidden','true')};
