const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const form=$('#proposalForm'),submit=$('#submitProposal'),memberList=$('#memberList'),add=$('#addMember'),concept=$('#conceptFile'),arts=$('#artFiles'),msg=$('#formMessage');
const MIN=3,MAX=10,MAX_CONCEPT=5*1024*1024,MAX_ART=10*1024*1024,MAX_TOTAL=25*1024*1024;
const ext=n=>(n||'').toLowerCase().split('.').pop(),val=id=>($(id)?.value||'').trim(),err=(id,t='')=>{const e=$(id);if(e)e.textContent=t},inv=(e,b)=>e?.classList.toggle('invalid',!!b);
function members(){return $$('.member-name',memberList).map(i=>i.value.trim())}
function renumber(){$$('.member',memberList).forEach((r,i)=>{ $('i',r).textContent=i+1;$('.member-name',r).placeholder='Nome completo do integrante '+(i+1)});add.disabled=$$('.member',memberList).length>=MAX}
function wireRemove(b){b.onclick=()=>{const rows=$$('.member',memberList);if(rows.length<=MIN){err('#membersError','É necessário manter pelo menos 3 integrantes.');return}b.closest('.member').remove();renumber();validate(false)}}
$$('.remove',memberList).forEach(wireRemove);renumber();
add.onclick=()=>{if($$('.member',memberList).length>=MAX)return;const n=$$('.member',memberList).length+1,d=document.createElement('div');d.className='member';d.innerHTML='<i>'+n+'</i><input class="member-name" name="members" type="text" placeholder="Nome completo do integrante '+n+'" required><button type="button" class="remove" aria-label="Remover integrante">×</button>';memberList.appendChild(d);wireRemove($('.remove',d));renumber();validate(false)};
function validate(show=true){let ok=true;
 const tn=val('#teamName');inv($('#teamName'),!tn);if(show||tn)err('#teamNameError',tn?'':'Informe o nome da equipe.');ok&&=!!tn;
 const ms=members(),filled=ms.filter(Boolean);const mok=filled.length>=MIN&&ms.every(Boolean);$$('.member-name').forEach(i=>inv(i,show&&!i.value.trim()));if(show||mok)err('#membersError',mok?'':filled.length<MIN?'Informe pelo menos 3 integrantes.':'Preencha ou remova os campos extras.');ok&&=mok;
 const digits=val('#phone').replace(/\D/g,''),pok=digits.length>=10&&digits.length<=13;inv($('#phone'),show&&!pok);if(show||pok)err('#phoneError',pok?'':'Informe um telefone válido com DDD.');ok&&=pok;
 const email=val('#email'),eok=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);inv($('#email'),show&&!eok);if(show||eok)err('#emailError',eok?'':'Informe um e-mail válido.');ok&&=eok;
 const cf=concept.files?.[0];let cok=!!cf,ce='';if(!cf)ce='Anexe a apresentação.';else if(!['pdf','ppt','pptx'].includes(ext(cf.name))){cok=false;ce='Use PDF, PPT ou PPTX.'}else if(cf.size>MAX_CONCEPT){cok=false;ce='Máximo de 5 MB.'}if(show||cok)err('#conceptError',cok?'':ce);ok&&=cok;
 const af=[...(arts.files||[])];let aok=af.length>0,ae='';if(!af.length)ae='Anexe pelo menos uma arte.';else if(af.some(f=>!['pdf','png','jpg','jpeg'].includes(ext(f.name)))){aok=false;ae='Use PDF, PNG, JPG ou JPEG.'}else if(af.some(f=>f.size>MAX_ART)){aok=false;ae='Máximo de 10 MB por arquivo.'}const total=(cf?.size||0)+af.reduce((s,f)=>s+f.size,0);if(aok&&total>MAX_TOTAL){aok=false;ae='O total dos anexos deve ser de no máximo 25 MB.'}if(show||aok)err('#artsError',aok?'':ae);ok&&=aok;
 submit.disabled=!ok;return ok}
$('#phone').addEventListener('input',e=>{let d=e.target.value.replace(/\D/g,'').slice(0,11);e.target.value=d.length<=2?(d?'('+d:''):d.length<=6?'('+d.slice(0,2)+') '+d.slice(2):d.length<=10?'('+d.slice(0,2)+') '+d.slice(2,6)+'-'+d.slice(6):'('+d.slice(0,2)+') '+d.slice(2,7)+'-'+d.slice(7);validate(false)});
form.addEventListener('input',e=>{if(e.target.id!=='phone')validate(false)});
concept.onchange=()=>{$('#conceptName').textContent=concept.files?.[0]?.name||'Nenhum arquivo selecionado.';$('#conceptBox').classList.toggle('has-file',!!concept.files?.[0]);validate(false)};
arts.onchange=()=>{const f=[...(arts.files||[])];$('#artsName').textContent=f.length?f.map(x=>x.name).join(' • '):'Nenhum arquivo selecionado.';$('#artsBox').classList.toggle('has-file',!!f.length);validate(false)};
function message(t,type='error'){msg.textContent=t;msg.className='message '+type;msg.scrollIntoView({behavior:'smooth',block:'center'})}
form.onsubmit=async e=>{e.preventDefault();msg.className='message';if(!validate(true)){message('Revise os campos obrigatórios antes de enviar.');return}submit.disabled=true;submit.textContent='Enviando...';try{const r=await fetch('/api/submit',{method:'POST',body:new FormData(form)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Não foi possível enviar a proposta.');$('#successText').textContent='A proposta foi enviada e uma cópia foi encaminhada para '+val('#email')+'.';$('#successModal').classList.add('open');$('#successModal').setAttribute('aria-hidden','false');message('Proposta enviada com sucesso.','success')}catch(x){message(x.message||'Ocorreu um erro no envio.')}finally{submit.innerHTML='Enviar proposta <span>→</span>';validate(false)}};
$('#closeSuccess').onclick=()=>{$('#successModal').classList.remove('open');$('#successModal').setAttribute('aria-hidden','true')};validate(false);